# Generated by Django 3.2.9 on 2021-11-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='logo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Logo URL'),
        ),
    ]
