# Generated by Django 3.2.9 on 2021-11-24 09:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='num_of_days',
            field=models.FloatField(verbose_name='number of days(Auto-calculated)'),
        ),
        migrations.AlterField(
            model_name='leaveday',
            name='additional_information',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaveday',
            name='leave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_days', to='leave.leave'),
        ),
    ]
